//------------------------------------------------------------------------------
//<auto-generated>
//This code is generated by the tool.
//Runtime version: 4.0.30319.18444
//
//Changes to this file may cause incorrect behavior if
//Regenerate the code and these changes will be lost.
//</auto-generated>
//------------------------------------------------------------------------------

namespace UniFTP.Common.Properties
{
    using System;


    ///<summary>
    ///A strongly typed resource class that looks up localized strings, etc.
    ///</summary>
    //This class is created by StronglyTypedResourceBuilder
    //Classes are automatically generated by tools similar to ResGen or Visual Studio.
    //To add or remove members, edit the . ResX file, and then rerun ResGen
    //(with /str as the command option), or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        ///<summary>
        ///Returns the cached ResourceManager instance used by this class.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniFTP.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        ///<summary>
        ///Use this strongly typed resource class to find all resources
        ///Overrides the CurrentUICulture property of the current thread.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
