//------------------------------------------------------------------------------
// <auto-generated>
//his code is generated by the tool.
//Runtime version: 4.0.30319.42000
//
//Changes to this file may cause incorrect behavior if
//Regenerate the code and these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFTP.Common.Localization
{
    using System;


    ///<summary>
    ///A strongly typed resource class that looks up localized strings, etc.
    ///</summary>
    //This class is created by StronglyTypedResourceBuilder
    //Classes are automatically generated by tools similar to ResGen or Visual Studio.
    //To add or remove members, edit the . ResX file, and then rerun ResGen
    //(with /str as the command option), or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FtpReplies
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtpReplies()
        {
        }

        ///<summary>
        ///Returns the cached ResourceManager instance used by this class.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniFTP.Common.Localization.FtpReplies", typeof(FtpReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        ///<summary>
        ///Use this strongly typed resource class to find all resources
        ///Overrides the CurrentUICulture property of the current thread.
        ///</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        ///<summary>
        ///Find something like Bad sequence of commands. Localized strings.
        ///</summary>
        public static string BAD_SEQUENCE
        {
            get
            {
                return ResourceManager.GetString("BAD_SEQUENCE", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like &quot;{0}&quot; is the current directory.
        ///</summary>
        public static string CURRENT_DIRECTORY
        {
            get
            {
                return ResourceManager.GetString("CURRENT_DIRECTORY", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Directory already exists.
        ///</summary>
        public static string DIRECTORY_EXISTS
        {
            get
            {
                return ResourceManager.GetString("DIRECTORY_EXISTS", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Directory not found.
        ///</summary>
        public static string DIRECTORY_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Enabling TLS Connection.
        ///</summary>
        public static string ENABLING_TLS
        {
            get
            {
                return ResourceManager.GetString("ENABLING_TLS", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like Entering Extended Passive Mode (||| {0}|) Localized strings.
        ///</summary>
        public static string ENTERING_EXTENDED_PASSIVE_MODE
        {
            get
            {
                return ResourceManager.GetString("ENTERING_EXTENDED_PASSIVE_MODE", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Entering Passive Mode ({0}, {1}, {2}, {3}, {4}, {5}).
        ///</summary>
        public static string ENTERING_PASSIVE_MODE
        {
            get
            {
                return ResourceManager.GetString("ENTERING_PASSIVE_MODE", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Extensions supported.
        ///</summary>
        public static string EXTENSIONS_SUPPORTED
        {
            get
            {
                return ResourceManager.GetString("EXTENSIONS_SUPPORTED", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Requested file action okay, completed.
        ///</summary>
        public static string FILE_ACTION_COMPLETE
        {
            get
            {
                return ResourceManager.GetString("FILE_ACTION_COMPLETE", resourceCulture);
            }
        }

        ///<summary>
        ///Look for a localized string like Requested file action not taken.
        ///</summary>
        public static string FILE_ACTION_NOT_TAKEN
        {
            get
            {
                return ResourceManager.GetString("FILE_ACTION_NOT_TAKEN", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like File not found.
        ///</summary>
        public static string FILE_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like User logged in.
        ///</summary>
        public static string LOGGED_IN
        {
            get
            {
                return ResourceManager.GetString("LOGGED_IN", resourceCulture);
            }
        }

        ///<summary>
        ///Find directory created like &quot;{0}&quot; Localized strings.
        ///</summary>
        public static string MAKE_DIRECTORY_SUCCESS
        {
            get
            {
                return ResourceManager.GetString("MAKE_DIRECTORY_SUCCESS", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Need more verification.
        ///</summary>
        public static string NEED_VERIFICATION
        {
            get
            {
                return ResourceManager.GetString("NEED_VERIFICATION", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Command not implemented.
        ///</summary>
        public static string NOT_IMPLEMENTED
        {
            get
            {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Command not implemented for that parameter.
        ///</summary>
        public static string NOT_IMPLEMENTED_FOR_PARAMETER
        {
            get
            {
                return ResourceManager.GetString("NOT_IMPLEMENTED_FOR_PARAMETER", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Not logged in.
        ///</summary>
        public static string NOT_LOGGED_IN
        {
            get
            {
                return ResourceManager.GetString("NOT_LOGGED_IN", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like OK.
        ///</summary>
        public static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like opening {0} mode data transfer for {1}.
        ///</summary>
        public static string OPENING_DATA_TRANSFER
        {
            get
            {
                return ResourceManager.GetString("OPENING_DATA_TRANSFER", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Opening {0} mode data transfer for {1} with SSL/TLS.
        ///</summary>
        public static string OPENING_SAFE_DATA_TRANSFER
        {
            get
            {
                return ResourceManager.GetString("OPENING_SAFE_DATA_TRANSFER", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Parameter {0} not recogonized.
        ///</summary>
        public static string PARAMETER_NOT_RECOGNIZED
        {
            get
            {
                return ResourceManager.GetString("PARAMETER_NOT_RECOGNIZED", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Service closing control connections.
        ///</summary>
        public static string QUIT
        {
            get
            {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Requested file action pending further information.
        ///</summary>
        public static string RENAME_FROM
        {
            get
            {
                return ResourceManager.GetString("RENAME_FROM", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like Restarting at {0}. Send STORE or RETRIEVE. Localized strings.
        ///</summary>
        public static string RESTART_FROM
        {
            get
            {
                return ResourceManager.GetString("RESTART_FROM", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like UniFTP Server Ready. (Ver.1.0) localized string.
        ///</summary>
        public static string SERVICE_READY
        {
            get
            {
                return ResourceManager.GetString("SERVICE_READY", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like Syntax error, command unrecognized. Localized strings.
        ///</summary>
        public static string SYNTAX_ERROR
        {
            get
            {
                return ResourceManager.GetString("SYNTAX_ERROR", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like UNIX Type: L8.
        ///</summary>
        public static string SYSTEM
        {
            get
            {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like TLS Auth failed. Localized strings.
        ///</summary>
        public static string TLS_AUTH_FAILED
        {
            get
            {
                return ResourceManager.GetString("TLS_AUTH_FAILED", resourceCulture);
            }
        }

        ///<summary>
        ///Find something like AUTH command is disabled. Localized strings.
        ///</summary>
        public static string TLS_DISABLED
        {
            get
            {
                return ResourceManager.GetString("TLS_DISABLED", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Transfer aborted.
        ///</summary>
        public static string TRANSFER_ABORTED
        {
            get
            {
                return ResourceManager.GetString("TRANSFER_ABORTED", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Closing data connection, transfer successful.
        ///</summary>
        public static string TRANSFER_SUCCESSFUL
        {
            get
            {
                return ResourceManager.GetString("TRANSFER_SUCCESSFUL", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Unable to open data connections.
        ///</summary>
        public static string UNABLE_TO_OPEN_DATA_CONNECTION
        {
            get
            {
                return ResourceManager.GetString("UNABLE_TO_OPEN_DATA_CONNECTION", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like Username ok, need password.
        ///</summary>
        public static string USER_OK
        {
            get
            {
                return ResourceManager.GetString("USER_OK", resourceCulture);
            }
        }

        ///<summary>
        ///Look for localized strings like UTF8 Encoding turned on.
        ///</summary>
        public static string UTF8_ENCODING_ON
        {
            get
            {
                return ResourceManager.GetString("UTF8_ENCODING_ON", resourceCulture);
            }
        }
    }
}
