//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFTP.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FtpReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtpReplies() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniFTP.Common.Localization.FtpReplies", typeof(FtpReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bad sequence of commands. 的本地化字符串。
        /// </summary>
        public static string BAD_SEQUENCE {
            get {
                return ResourceManager.GetString("BAD_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is the current directory 的本地化字符串。
        /// </summary>
        public static string CURRENT_DIRECTORY {
            get {
                return ResourceManager.GetString("CURRENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory already exists 的本地化字符串。
        /// </summary>
        public static string DIRECTORY_EXISTS {
            get {
                return ResourceManager.GetString("DIRECTORY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory not found 的本地化字符串。
        /// </summary>
        public static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling TLS Connection 的本地化字符串。
        /// </summary>
        public static string ENABLING_TLS {
            get {
                return ResourceManager.GetString("ENABLING_TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entering Extended Passive Mode (|||{0}|) 的本地化字符串。
        /// </summary>
        public static string ENTERING_EXTENDED_PASSIVE_MODE {
            get {
                return ResourceManager.GetString("ENTERING_EXTENDED_PASSIVE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entering Passive Mode ({0},{1},{2},{3},{4},{5}) 的本地化字符串。
        /// </summary>
        public static string ENTERING_PASSIVE_MODE {
            get {
                return ResourceManager.GetString("ENTERING_PASSIVE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions supported 的本地化字符串。
        /// </summary>
        public static string EXTENSIONS_SUPPORTED {
            get {
                return ResourceManager.GetString("EXTENSIONS_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested file action okay, completed 的本地化字符串。
        /// </summary>
        public static string FILE_ACTION_COMPLETE {
            get {
                return ResourceManager.GetString("FILE_ACTION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested file action not taken 的本地化字符串。
        /// </summary>
        public static string FILE_ACTION_NOT_TAKEN {
            get {
                return ResourceManager.GetString("FILE_ACTION_NOT_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found 的本地化字符串。
        /// </summary>
        public static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User logged in 的本地化字符串。
        /// </summary>
        public static string LOGGED_IN {
            get {
                return ResourceManager.GetString("LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need more verification 的本地化字符串。
        /// </summary>
        public static string NEED_VERIFICATION {
            get {
                return ResourceManager.GetString("NEED_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command not implemented 的本地化字符串。
        /// </summary>
        public static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command not implemented for that parameter 的本地化字符串。
        /// </summary>
        public static string NOT_IMPLEMENTED_FOR_PARAMETER {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED_FOR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not logged in 的本地化字符串。
        /// </summary>
        public static string NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening {0} mode data transfer for {1} 的本地化字符串。
        /// </summary>
        public static string OPENING_DATA_TRANSFER {
            get {
                return ResourceManager.GetString("OPENING_DATA_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter {0} not recogonized 的本地化字符串。
        /// </summary>
        public static string PARAMETER_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("PARAMETER_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service closing control connection 的本地化字符串。
        /// </summary>
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested file action pending further information 的本地化字符串。
        /// </summary>
        public static string RENAME_FROM {
            get {
                return ResourceManager.GetString("RENAME_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting at {0}. Send STORE or RETRIEVE. 的本地化字符串。
        /// </summary>
        public static string RESTART_FROM {
            get {
                return ResourceManager.GetString("RESTART_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UniFTP Server Ready. (Ver.0.1) 的本地化字符串。
        /// </summary>
        public static string SERVICE_READY {
            get {
                return ResourceManager.GetString("SERVICE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax error, command unrecognized. 的本地化字符串。
        /// </summary>
        public static string SYNTAX_ERROR {
            get {
                return ResourceManager.GetString("SYNTAX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UNIX Type: L8 的本地化字符串。
        /// </summary>
        public static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TLS Auth failed. 的本地化字符串。
        /// </summary>
        public static string TLS_AUTH_FAILED {
            get {
                return ResourceManager.GetString("TLS_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AUTH command is disabled. 的本地化字符串。
        /// </summary>
        public static string TLS_DISABLED {
            get {
                return ResourceManager.GetString("TLS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer aborted 的本地化字符串。
        /// </summary>
        public static string TRANSFER_ABORTED {
            get {
                return ResourceManager.GetString("TRANSFER_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closing data connection, transfer successful 的本地化字符串。
        /// </summary>
        public static string TRANSFER_SUCCESSFUL {
            get {
                return ResourceManager.GetString("TRANSFER_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open data connection 的本地化字符串。
        /// </summary>
        public static string UNABLE_TO_OPEN_DATA_CONNECTION {
            get {
                return ResourceManager.GetString("UNABLE_TO_OPEN_DATA_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username ok, need password 的本地化字符串。
        /// </summary>
        public static string USER_OK {
            get {
                return ResourceManager.GetString("USER_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF8 Encoding turned on 的本地化字符串。
        /// </summary>
        public static string UTF8_ENCODING_ON {
            get {
                return ResourceManager.GetString("UTF8_ENCODING_ON", resourceCulture);
            }
        }
    }
}
